### ISSUE TITLE
Page sections id & class have a slash

### ISSUE THREAD

**Issue by mariosmaselli** [baptistebriel/biggie#219]
Hey I just made a fresh install and it looks like now on the sections the the id & class are getting and extra "/"  class and id look like this `page page-section/one`

**Comment by baptistebriel** [comment]
Hey @mariosmaselli, are you using the 1.1.2 version?
I just did a fresh clone myself and seems like I don't have any `/`;

![screen shot 2017-02-20 at 9 47 59 am](https://cloud.githubusercontent.com/assets/2464663/23136479/c0b5eec8-f751-11e6-9dd4-4bf21d1a02ca.png)

Look at the [page.js](https://github.com/baptistebriel/biggie/blob/master/assets/js/utils/biggie/page.js#L10) file under `/utils/biggie`. Let me know!

**Comment by mariosmaselli** [comment]
Apparently I have 1.1.0 I will try to update now!

**Comment by mariosmaselli** [comment]
Ok, thanks now everything is working! Sorry for not checking out current version...
